# Generated by Django 5.2 on 2025-05-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('economy', 'Economy'), ('standard', 'Standard'), ('luxury', 'Luxury'), ('suv', 'SUV')], default='standard', max_length=20),
        ),
    ]
