# Generated by Django 5.2 on 2025-05-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='featured_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
